port: ":8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "delivery"
  sslmode: "disable"

email:
  host: "smtp.mail.ru"
  port: "465"
  username: "reg_deliveryhouse@mail.ru"
  password: "wjVC1MJX7zWgH2ZRgKv2"