port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "delivery"
  sslmode: "disable"
  password: "12345"

email:
  host: "smtp.yandex.ru"
  port: "465"
  username: "callmehorhe"
  password: "kofzgklynguhlvit"